[package]
    name = "wasm-core"
    version = "0.1.0"
    edition = "2021"
    authors = ["Artem <flamesoff@example.com>"]
    description = "A sample project with wasm-pack"
    license = "MIT/Apache-2.0"
    repository = "https://github.com/f1am3d/hello-wasm"

[lib]
    crate-type = ["cdylib"]
    path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.83"